/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/game-console': RouteRecordInfo<
      '/game-console',
      '/game-console',
      Record<never, never>,
      Record<never, never>,
      | '/game-console/chicken-fly'
      | '/game-console/fox-and-mouse'
      | '/game-console/lobby'
      | '/game-console/the-first-penguin'
    >,
    '/game-console/chicken-fly': RouteRecordInfo<
      '/game-console/chicken-fly',
      '/game-console/chicken-fly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-console/fox-and-mouse': RouteRecordInfo<
      '/game-console/fox-and-mouse',
      '/game-console/fox-and-mouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-console/lobby': RouteRecordInfo<
      '/game-console/lobby',
      '/game-console/lobby',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-console/the-first-penguin': RouteRecordInfo<
      '/game-console/the-first-penguin',
      '/game-console/the-first-penguin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/player-gamepad': RouteRecordInfo<
      '/player-gamepad',
      '/player-gamepad',
      Record<never, never>,
      Record<never, never>,
      | '/player-gamepad/chicken-fly'
      | '/player-gamepad/fox-and-mouse'
      | '/player-gamepad/lobby'
      | '/player-gamepad/the-first-penguin'
    >,
    '/player-gamepad/chicken-fly': RouteRecordInfo<
      '/player-gamepad/chicken-fly',
      '/player-gamepad/chicken-fly',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/player-gamepad/fox-and-mouse': RouteRecordInfo<
      '/player-gamepad/fox-and-mouse',
      '/player-gamepad/fox-and-mouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/player-gamepad/lobby': RouteRecordInfo<
      '/player-gamepad/lobby',
      '/player-gamepad/lobby',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/player-gamepad/the-first-penguin': RouteRecordInfo<
      '/player-gamepad/the-first-penguin',
      '/player-gamepad/the-first-penguin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/game-console.vue': {
      routes:
        | '/game-console'
        | '/game-console/chicken-fly'
        | '/game-console/fox-and-mouse'
        | '/game-console/lobby'
        | '/game-console/the-first-penguin'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/game-console/chicken-fly.vue': {
      routes:
        | '/game-console/chicken-fly'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-console/fox-and-mouse.vue': {
      routes:
        | '/game-console/fox-and-mouse'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-console/lobby.vue': {
      routes:
        | '/game-console/lobby'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-console/the-first-penguin.vue': {
      routes:
        | '/game-console/the-first-penguin'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/player-gamepad.vue': {
      routes:
        | '/player-gamepad'
        | '/player-gamepad/chicken-fly'
        | '/player-gamepad/fox-and-mouse'
        | '/player-gamepad/lobby'
        | '/player-gamepad/the-first-penguin'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/player-gamepad/chicken-fly.vue': {
      routes:
        | '/player-gamepad/chicken-fly'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/player-gamepad/fox-and-mouse.vue': {
      routes:
        | '/player-gamepad/fox-and-mouse'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/player-gamepad/lobby.vue': {
      routes:
        | '/player-gamepad/lobby'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/player-gamepad/the-first-penguin.vue': {
      routes:
        | '/player-gamepad/the-first-penguin'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
